[2024-03-24 09:00:05,286] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.get_weather_data 2024-03-24T08:59:00+00:00 [queued]>
[2024-03-24 09:00:05,302] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.get_weather_data 2024-03-24T08:59:00+00:00 [queued]>
[2024-03-24 09:00:05,303] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-03-24 09:00:05,304] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-03-24 09:00:05,305] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-03-24 09:00:05,329] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): get_weather_data> on 2024-03-24T08:59:00+00:00
[2024-03-24 09:00:05,343] {standard_task_runner.py:52} INFO - Started process 18457 to run task
[2024-03-24 09:00:05,352] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'get_weather_data', '2024-03-24T08:59:00+00:00', '--job-id', '906', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/file.py', '--cfg-path', '/tmp/tmpnkne58df', '--error-file', '/tmp/tmphily7pap']
[2024-03-24 09:00:05,354] {standard_task_runner.py:77} INFO - Job 906: Subtask get_weather_data
[2024-03-24 09:00:05,457] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.get_weather_data 2024-03-24T08:59:00+00:00 [running]> on host ce3400b6b8c4
[2024-03-24 09:00:05,578] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=get_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-24T08:59:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-24T08:59:00+00:00
[2024-03-24 09:00:10,115] {python.py:151} INFO - Done. Returned value was: None
[2024-03-24 09:00:10,140] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=get_weather_data, execution_date=20240324T085900, start_date=20240324T090005, end_date=20240324T090010
[2024-03-24 09:00:10,231] {taskinstance.py:1265} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-03-24 09:00:10,275] {local_task_job.py:151} INFO - Task exited with return code 0
