[2024-03-24 04:57:05,985] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.get_weather_data 2024-03-24T04:56:00+00:00 [queued]>
[2024-03-24 04:57:06,393] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.get_weather_data 2024-03-24T04:56:00+00:00 [queued]>
[2024-03-24 04:57:06,484] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-03-24 04:57:06,546] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-03-24 04:57:06,829] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-03-24 04:57:07,096] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): get_weather_data> on 2024-03-24T04:56:00+00:00
[2024-03-24 04:57:07,327] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'get_weather_data', '2024-03-24T04:56:00+00:00', '--job-id', '34', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/file.py', '--cfg-path', '/tmp/tmp_tyo6lqj', '--error-file', '/tmp/tmpwpkuoer0']
[2024-03-24 04:57:07,321] {standard_task_runner.py:52} INFO - Started process 2757 to run task
[2024-03-24 04:57:07,355] {standard_task_runner.py:77} INFO - Job 34: Subtask get_weather_data
[2024-03-24 04:57:07,894] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.get_weather_data 2024-03-24T04:56:00+00:00 [running]> on host ce3400b6b8c4
[2024-03-24 04:57:09,679] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=get_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-24T04:56:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-24T04:56:00+00:00
[2024-03-24 04:57:10,380] {python.py:151} INFO - Done. Returned value was: None
[2024-03-24 04:57:10,420] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=get_weather_data, execution_date=20240324T045600, start_date=20240324T045706, end_date=20240324T045710
[2024-03-24 04:57:10,642] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-24 04:57:10,768] {local_task_job.py:151} INFO - Task exited with return code 0
