[2024-03-24 08:58:02,706] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.get_weather_data 2024-03-24T08:57:00+00:00 [queued]>
[2024-03-24 08:58:02,759] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.get_weather_data 2024-03-24T08:57:00+00:00 [queued]>
[2024-03-24 08:58:02,760] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-03-24 08:58:02,762] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-03-24 08:58:02,763] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-03-24 08:58:02,795] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): get_weather_data> on 2024-03-24T08:57:00+00:00
[2024-03-24 08:58:02,802] {standard_task_runner.py:52} INFO - Started process 18299 to run task
[2024-03-24 08:58:02,810] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'get_weather_data', '2024-03-24T08:57:00+00:00', '--job-id', '892', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/file.py', '--cfg-path', '/tmp/tmpz5lsamv2', '--error-file', '/tmp/tmp7z5ws6gc']
[2024-03-24 08:58:02,812] {standard_task_runner.py:77} INFO - Job 892: Subtask get_weather_data
[2024-03-24 08:58:02,884] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.get_weather_data 2024-03-24T08:57:00+00:00 [running]> on host ce3400b6b8c4
[2024-03-24 08:58:02,961] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=get_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2024-03-24T08:57:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-24T08:57:00+00:00
[2024-03-24 08:58:04,276] {python.py:151} INFO - Done. Returned value was: None
[2024-03-24 08:58:04,302] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=get_weather_data, execution_date=20240324T085700, start_date=20240324T085802, end_date=20240324T085804
[2024-03-24 08:58:04,402] {taskinstance.py:1265} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-03-24 08:58:04,428] {local_task_job.py:151} INFO - Task exited with return code 0
