[2024-03-24 08:58:09,490] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.transform_all 2024-03-24T08:57:00+00:00 [queued]>
[2024-03-24 08:58:09,528] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: weather_data_pipeline.transform_all 2024-03-24T08:57:00+00:00 [queued]>
[2024-03-24 08:58:09,529] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-03-24 08:58:09,530] {taskinstance.py:1088} INFO - Starting attempt 1 of 2
[2024-03-24 08:58:09,531] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-03-24 08:58:09,594] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): transform_all> on 2024-03-24T08:57:00+00:00
[2024-03-24 08:58:09,609] {standard_task_runner.py:52} INFO - Started process 18318 to run task
[2024-03-24 08:58:09,644] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'transform_all', '2024-03-24T08:57:00+00:00', '--job-id', '893', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/file.py', '--cfg-path', '/tmp/tmps09j8hur', '--error-file', '/tmp/tmp6qexkcje']
[2024-03-24 08:58:09,654] {standard_task_runner.py:77} INFO - Job 893: Subtask transform_all
[2024-03-24 08:58:09,860] {logging_mixin.py:104} INFO - Running <TaskInstance: weather_data_pipeline.transform_all 2024-03-24T08:57:00+00:00 [running]> on host ce3400b6b8c4
[2024-03-24 08:58:10,270] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weather_data_pipeline
AIRFLOW_CTX_TASK_ID=transform_all
AIRFLOW_CTX_EXECUTION_DATE=2024-03-24T08:57:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-03-24T08:57:00+00:00
[2024-03-24 08:58:11,566] {python.py:151} INFO - Done. Returned value was: None
[2024-03-24 08:58:11,606] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=weather_data_pipeline, task_id=transform_all, execution_date=20240324T085700, start_date=20240324T085809, end_date=20240324T085811
[2024-03-24 08:58:11,707] {taskinstance.py:1265} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2024-03-24 08:58:11,752] {local_task_job.py:151} INFO - Task exited with return code 0
